# Форма регистрации
reg_form = '.Auth_form__3qKeq'
input_name = './/label[text()="Имя"]/following-sibling::input'
input_email = './/label[text()="Email"]/following-sibling::input'
input_password = 'Пароль'
reg_button = './/button[text()="Зарегистрироваться"]'
auth_form = '.Auth_login__3hAey'
enter_button = './/button[text()="Войти"]'
invalid_passwd_messg = '.input__error'
main_page_enter_acc_button = './/button[text()="Войти в аккаунт"]'
main_page_make_order_button = './/button[text()="Оформить заказ"]'
personal_acc = './/p[text()="Личный Кабинет"]'
auth_link = '.Auth_link__1fOlj'
login_page_forgot_passwd_link = './/a[@href="/forgot-password"]'
account_list = '.Account_list__3KQQf'
profile = './/a[text()="Профиль"]'
constructor = './/p[text()="Конструктор"]'
main_logo = '.AppHeader_header__nav__g5hnF div'
logout_button = './/button[text()="Выход"]'
sause_section = './/span[text()="Соусы"]/parent::div'
filling_section = './/span[text()="Начинки"]/parent::div'
bun_section = './/span[text()="Булки"]/parent::div'
